-- The key bit for library / patron access to ebsco articles
-- (library_zserver_credentials to *search*, this stuff to *look at the articles*

alter table libraries add column ebsco_user varchar(40);
alter table libraries add column ebsco_pass varchar(40);

update libraries set ebsco_user='bwpl', ebsco_pass='bwpl' where lid = (select lid from libraries where library like 'Bette Winner Public Library');
update libraries set ebsco_user='s6091479', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bibliothèque Allard');
update libraries set ebsco_user='s5772290', ebsco_pass='Password' where lid = (select lid from libraries where library like 'Bibliotheque Allard - Beaches');
update libraries set ebsco_user='s6151884', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bibliothèque Montcalm');
update libraries set ebsco_user='ndbiblio', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bibliothèque Pere Champagne');
update libraries set ebsco_user='s6314735', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bibliothèque Ritchot - Main');
update libraries set ebsco_user='sal', ebsco_pass='adolphe' where lid = (select lid from libraries where library like 'Bibliothèque Ritchot - St. Adolphe');
update libraries set ebsco_user='saint', ebsco_pass='agathe' where lid = (select lid from libraries where library like 'Bibliothèque Ritchot - Ste. Agathe');
update libraries set ebsco_user='s6393310', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bibliothèque Saint-Claude');
update libraries set ebsco_user='s6416082', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bibliothèque Saint-Joachim Library');
update libraries set ebsco_user='s6463631', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bibliothèque Somerset Library');
update libraries set ebsco_user='s6481383', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bibliothèque Ste. Anne');
update libraries set ebsco_user='s6080402', ebsco_pass='password' where lid = (select lid from libraries where library like 'Boissevain and Morton Regional Library');
update libraries set ebsco_user='borderelkhorn', ebsco_pass='BorderRegional' where lid = (select lid from libraries where library like 'Border Regional Library - Elkhorn');
update libraries set ebsco_user='bordervirden', ebsco_pass='BorderRegional' where lid = (select lid from libraries where library like 'Border Regional Library - Main');
update libraries set ebsco_user='bordermcauley', ebsco_pass='BorderRegional' where lid = (select lid from libraries where library like 'Border Regional Library - McAuley');
update libraries set ebsco_user='s1035547', ebsco_pass='password' where lid = (select lid from libraries where library like 'Boyne Regional Library');
update libraries set ebsco_user='s6568841', ebsco_pass='password' where lid = (select lid from libraries where library like 'Bren Del Win Centennial Library');
update libraries set ebsco_user='s4239300', ebsco_pass='password' where lid = (select lid from libraries where library like 'Brokenhead River Regional Library');
update libraries set ebsco_user='s6722383', ebsco_pass='password' where lid = (select lid from libraries where library like 'Churchill Public Library');
update libraries set ebsco_user='s6763302', ebsco_pass='password' where lid = (select lid from libraries where library like 'Emerson Library');
update libraries set ebsco_user='mel', ebsco_pass='mel' where lid = (select lid from libraries where library like 'Eriksdale Public Library');
update libraries set ebsco_user='arborg', ebsco_pass='arborg' where lid = (select lid from libraries where library like 'Evergreen Regional Library - Arborg');
update libraries set ebsco_user='evergreenreg', ebsco_pass='trial' where lid = (select lid from libraries where library like 'Evergreen Regional Library - Main');
update libraries set ebsco_user='riverton', ebsco_pass='riverton' where lid = (select lid from libraries where library like 'Evergreen Regional Library - Riverton');
update libraries set ebsco_user='s6829351', ebsco_pass='password' where lid = (select lid from libraries where library like 'Flin Flon Public Library');
update libraries set ebsco_user='s6859026', ebsco_pass='password' where lid = (select lid from libraries where library like 'Glenwood & Souris Regional Library');
update libraries set ebsco_user='s6875882', ebsco_pass='password' where lid = (select lid from libraries where library like 'Headingley Municipal Library');
update libraries set ebsco_user='jake', ebsco_pass='ebscotrial' where lid = (select lid from libraries where library like 'Jake Epp Library');
update libraries set ebsco_user='s6110155', ebsco_pass='password' where lid = (select lid from libraries where library like 'Jolys Regional Library - Main');
update libraries set ebsco_user='saint', ebsco_pass='malo' where lid = (select lid from libraries where library like 'Jolys Regional Library - St. Malo');
update libraries set ebsco_user='s6917328', ebsco_pass='password' where lid = (select lid from libraries where library like 'Lac Du Bonnet Regional Library');
update libraries set ebsco_user='cartwright', ebsco_pass='Cartwright' where lid = (select lid from libraries where library like 'Lakeland Regional Library - Cartwright');
update libraries set ebsco_user='s8921274', ebsco_pass='password' where lid = (select lid from libraries where library like 'Lakeland Regional Library - Main');
update libraries set ebsco_user='s6970871', ebsco_pass='password' where lid = (select lid from libraries where library like 'Leaf Rapids Public Library');
update libraries set ebsco_user='s6993334', ebsco_pass='password' where lid = (select lid from libraries where library like 'Lynn Lake Centennial Library');
update libraries set ebsco_user='s7007965', ebsco_pass='password' where lid = (select lid from libraries where library like 'Manitou Public Library');
update libraries set ebsco_user='minnedosarl', ebsco_pass='minnedosarl' where lid = (select lid from libraries where library like 'Minnedosa Regional Library');
update libraries set ebsco_user='s7049550', ebsco_pass='password' where lid = (select lid from libraries where library like 'North Norfolk-MacGregor Library');
update libraries set ebsco_user='benito', ebsco_pass='benito' where lid = (select lid from libraries where library like 'North-West Regional Library - Benito Branch');
update libraries set ebsco_user='s7071953', ebsco_pass='password' where lid = (select lid from libraries where library like 'North-West Regional Library - Main');
update libraries set ebsco_user='birch', ebsco_pass='river' where lid = (select lid from libraries where library like 'Parkland Regional Library - Birch River');
update libraries set ebsco_user='birtle', ebsco_pass='birtle' where lid = (select lid from libraries where library like 'Parkland Regional Library - Birtle');
update libraries set ebsco_user='bowsman', ebsco_pass='bowsman' where lid = (select lid from libraries where library like 'Parkland Regional Library - Bowsman');
update libraries set ebsco_user='s4732742', ebsco_pass='password' where lid = (select lid from libraries where library like 'Parkland Regional Library - Dauphin');
update libraries set ebsco_user='s6085216', ebsco_pass='password' where lid = (select lid from libraries where library like 'Parkland Regional Library - Erickson');
update libraries set ebsco_user='s9052086', ebsco_pass='password' where lid = (select lid from libraries where library like 'Parkland Regional Library - Foxwarren');
update libraries set ebsco_user='gilbert', ebsco_pass='plains' where lid = (select lid from libraries where library like 'Parkland Regional Library - Gilbert Plains');
update libraries set ebsco_user='grandview', ebsco_pass='grandview' where lid = (select lid from libraries where library like 'Parkland Regional Library - Grandview');
update libraries set ebsco_user='hamiota', ebsco_pass='hamiota' where lid = (select lid from libraries where library like 'Parkland Regional Library - Hamiota');
update libraries set ebsco_user='langruth', ebsco_pass='langruth' where lid = (select lid from libraries where library like 'Parkland Regional Library - Langruth');
update libraries set ebsco_user='mccreary', ebsco_pass='mccreary' where lid = (select lid from libraries where library like 'Parkland Regional Library - McCreary');
update libraries set ebsco_user='minitonas', ebsco_pass='minitonas' where lid = (select lid from libraries where library like 'Parkland Regional Library - Minitonas');
update libraries set ebsco_user='s9233164', ebsco_pass='password' where lid = (select lid from libraries where library like 'Parkland Regional Library - Ochre River');
update libraries set ebsco_user='roblin', ebsco_pass='roblin' where lid = (select lid from libraries where library like 'Parkland Regional Library - Roblin');
update libraries set ebsco_user='s7725300', ebsco_pass='password' where lid = (select lid from libraries where library like 'Parkland Regional Library - Shoal Lake');
update libraries set ebsco_user='siglunes', ebsco_pass='siglunes' where lid = (select lid from libraries where library like 'Parkland Regional Library - Siglunes');
update libraries set ebsco_user='strathclair', ebsco_pass='strathclair' where lid = (select lid from libraries where library like 'Parkland Regional Library - Strathclair');
update libraries set ebsco_user='winnipegosis', ebsco_pass='winnipegosis' where lid = (select lid from libraries where library like 'Parkland Regional Library - Winnipegosis');
update libraries set ebsco_user='s7132074', ebsco_pass='password' where lid = (select lid from libraries where library like 'Pauline Johnson Library');
update libraries set ebsco_user='pilot', ebsco_pass='mound' where lid = (select lid from libraries where library like 'Pilot Mound Public Library - Pilot Mound');
update libraries set ebsco_user='s1035842', ebsco_pass='password' where lid = (select lid from libraries where library like 'Pinawa Public Library');
update libraries set ebsco_user='s7165579', ebsco_pass='password' where lid = (select lid from libraries where library like 'Portage La Prairie Regional Library');
update libraries set ebsco_user='s7183384', ebsco_pass='password' where lid = (select lid from libraries where library like 'Prairie Crocus Regional Library');
update libraries set ebsco_user='s5521720', ebsco_pass='password' where lid = (select lid from libraries where library like 'Public Library Services');
update libraries set ebsco_user='s5826566', ebsco_pass='password' where lid = (select lid from libraries where library like 'Rapid City Regional Library');
update libraries set ebsco_user='redrivernorth', ebsco_pass='steelers' where lid = (select lid from libraries where library like 'Red River North Regional Library');
update libraries set ebsco_user='reston', ebsco_pass='trial' where lid = (select lid from libraries where library like 'Reston District Library');
update libraries set ebsco_user='s7204480', ebsco_pass='password' where lid = (select lid from libraries where library like 'R.M. of Argyle Public Library');
update libraries set ebsco_user='s5913667', ebsco_pass='password' where lid = (select lid from libraries where library like 'Rossburn Regional Library');
update libraries set ebsco_user='binscarth', ebsco_pass='binscarth' where lid = (select lid from libraries where library like 'Russell & District Library - Binscarth');
update libraries set ebsco_user='s1036253', ebsco_pass='password' where lid = (select lid from libraries where library like 'Russell & District Regional Library - Main');
update libraries set ebsco_user='s6208129', ebsco_pass='password' where lid = (select lid from libraries where library like 'Snow Lake Community Library');
update libraries set ebsco_user='s6353086', ebsco_pass='password' where lid = (select lid from libraries where library like 'South Central Regional Library - Altona');
update libraries set ebsco_user='s5521766', ebsco_pass='p0011655' where lid = (select lid from libraries where library like 'South Central Regional Library - Morden');
update libraries set ebsco_user='s6465864', ebsco_pass='password' where lid = (select lid from libraries where library like 'South Central Regional Library - Winkler');
update libraries set ebsco_user='s1036635', ebsco_pass='password' where lid = (select lid from libraries where library like 'South Interlake Regional Library - Main');
update libraries set ebsco_user='teulon', ebsco_pass='teulon' where lid = (select lid from libraries where library like 'South Interlake Regional Library - Teulon');
update libraries set ebsco_user='s8921298', ebsco_pass='password' where lid = (select lid from libraries where library like 'Southwestern Manitoba Regional Library - Main');
update libraries set ebsco_user='napinka', ebsco_pass='napinka' where lid = (select lid from libraries where library like 'Southwestern Manitoba Regional Library - Napinka');
update libraries set ebsco_user='s2487764', ebsco_pass='password' where lid = (select lid from libraries where library like 'Southwestern Manitoba Regional Library - Pierson');
update libraries set ebsco_user='library', ebsco_pass='reader' where lid = (select lid from libraries where library like 'Ste. Rose Regional Library');
update libraries set ebsco_user='s6571842', ebsco_pass='password' where lid = (select lid from libraries where library like 'The Pas Regional Library');
update libraries set ebsco_user='s8914567', ebsco_pass='password' where lid = (select lid from libraries where library like 'Thompson Public Library');
update libraries set ebsco_user='s6683258', ebsco_pass='password' where lid = (select lid from libraries where library like 'Valley Regional Library');
update libraries set ebsco_user='s6825002', ebsco_pass='password' where lid = (select lid from libraries where library like 'Victoria Municipal Library');
update libraries set ebsco_user='s5521791', ebsco_pass='p0011656' where lid = (select lid from libraries where library like 'Western Manitoba Regional Library - Brandon');
update libraries set ebsco_user='carberry', ebsco_pass='carberry' where lid = (select lid from libraries where library like 'Western Manitoba Regional Library - Carberry/North Cypress');
update libraries set ebsco_user='glenboro', ebsco_pass='glenboro' where lid = (select lid from libraries where library like 'Western Manitoba Regional  Library - Glenboro/South Cypress');
update libraries set ebsco_user='s6844425', ebsco_pass='password' where lid = (select lid from libraries where library like 'Western Manitoba Regional  Library - Neepawa');
