update libraries set town='Lundar', region='INTERLAKE' where library like 'Pauline Johnson Library';
update libraries set town='Ile des Chenes', region='EASTMAN' where library like 'Bibliothèque Ritchot - Main';
update libraries set town='Notre Dame de Lourdes', region='CENTRAL' where library like 'Bibliothèque Pere Champagne';
update libraries set town='Saint-Jean-Baptiste', region='CENTRAL' where library like 'Bibliothèque Montcalm';
update libraries set town='St Georges', region='EASTMAN' where library like 'Bibliothèque Allard';
update libraries set town='St. Adolphe', region='EASTMAN' where library like 'Bibliothèque Ritchot - St. Adolphe';
update libraries set town='Ste. Agathe', region='EASTMAN' where library like 'Bibliothèque Ritchot - Ste. Agathe';
update libraries set town='La Broquerie', region='EASTMAN' where library like 'Bibliothèque Saint-Joachim Library';
update libraries set town='Ste. Anne', region='EASTMAN' where library like 'Bibliothèque Ste. Anne';
update libraries set town='Somerset', region='CENTRAL' where library like 'Bibliothèque Somerset Library';
update libraries set town='Boissevain', region='WESTMAN' where library like 'Boissevain and Morton Regional Library';
update libraries set town='Elkhorn', region='WESTMAN' where library like 'Border Regional Library - Elkhorn';
update libraries set town='McAuley', region='WESTMAN' where library like 'Border Regional Library - McAuley';
update libraries set town='Carman', region='CENTRAL' where library like 'Boyne Regional Library';
update libraries set town='Deloriane', region='WESTMAN' where library like 'Bren Del Win Centennial Library';
update libraries set town='Beausejour', region='EASTMAN' where library like 'Brokenhead River Regional Library';
update libraries set town='Eriksdale', region='INTERLAKE' where library like 'Eriksdale Public Library';
update libraries set town='Churchill', region='NORMAN' where library like 'Churchill Public Library';
update libraries set town='Gimli', region='INTERLAKE' where library like 'Evergreen Regional Library - Main';
update libraries set town='Arborg', region='INTERLAKE' where library like 'Evergreen Regional Library - Arborg';
update libraries set town='Riverton', region='INTERLAKE' where library like 'Evergreen Regional Library - Riverton';
update libraries set town='Flin Flon', region='NORMAN' where library like 'Flin Flon Public Library';
update libraries set town='Gillam', region='NORMAN' where library like 'Bette Winner Public Library';
update libraries set town='Souris', region='WESTMAN' where library like 'Glenwood & Souris Regional Library';
update libraries set town='Headingly', region='CENTRAL' where library like 'Headingley Municipal Library';
update libraries set town='St. Pierre', region='EASTMAN' where library like 'Jolys Regional Library - Main';
update libraries set town='St. Malo', region='EASTMAN' where library like 'Jolys Regional Library - St. Malo';
update libraries set town='Lac du Bonnet', region='EASTMAN' where library like 'Lac Du Bonnet Regional Library';
update libraries set town='Killarney', region='WESTMAN' where library like 'Lakeland Regional Library - Main';
update libraries set town='Cartwright', region='CENTRAL' where library like 'Lakeland Regional Library - Cartwright';
update libraries set town='Pilot Mound', region='CENTRAL' where library like 'Pilot Mound Public Library - Pilot Mound';
update libraries set town='Leaf Rapids', region='NORMAN' where library like 'Leaf Rapids Public Library';
update libraries set town='Lynn Lake', region='NORMAN' where library like 'Lynn Lake Centennial Library';
update libraries set town='Manitou', region='CENTRAL' where library like 'Manitou Public Library';
update libraries set town='MacGregor', region='CENTRAL' where library like 'North Norfolk-MacGregor Library';
update libraries set town='Swan River', region='PARKLAND' where library like 'North-West Regional Library - Main';
update libraries set town='Benito', region='PARKLAND' where library like 'North-West Regional Library - Benito Branch';
update libraries set town='Birch River', region='PARKLAND' where library like 'Parkland Regional Library - Birch River';
update libraries set town='Birtle', region='WESTMAN' where library like 'Parkland Regional Library - Birtle';
update libraries set town='Bowsman', region='PARKLAND' where library like 'Parkland Regional Library - Bowsman';
update libraries set town='Dauphin', region='PARKLAND' where library like 'Parkland Regional Library - Dauphin';
update libraries set town='Erickson', region='WESTMAN' where library like 'Parkland Regional Library - Erickson';
update libraries set town='Foxwarren', region='WESTMAN' where library like 'Parkland Regional Library - Foxwarren';
update libraries set town='Gilbert Plains', region='PARKLAND' where library like 'Parkland Regional Library - Gilbert Plains';
update libraries set town='Gladstone', region='CENTRAL' where library like 'Parkland Regional Library - Gladstone';
update libraries set town='Grandview', region='PARKLAND' where library like 'Parkland Regional Library - Grandview';
update libraries set town='Hamiota', region='WESTMAN' where library like 'Parkland Regional Library - Hamiota';
update libraries set town='Langruth', region='CENTRAL' where library like 'Parkland Regional Library - Langruth';
update libraries set town='McCreary', region='PARKLAND' where library like 'Parkland Regional Library - McCreary';
update libraries set town='Minitonas', region='PARKLAND' where library like 'Parkland Regional Library - Minitonas';
update libraries set town='Ochre River', region='PARKLAND' where library like 'Parkland Regional Library - Ochre River';
update libraries set town='Roblin', region='PARKLAND' where library like 'Parkland Regional Library - Roblin';
update libraries set town='Shoal Lake', region='WESTMAN' where library like 'Parkland Regional Library - Shoal Lake';
update libraries set town='Siglunes', region='CENTRAL' where library like 'Parkland Regional Library - Siglunes';
update libraries set town='Winnipegosis', region='PARKLAND' where library like 'Parkland Regional Library - Winnipegosis';
update libraries set town='Pinawa', region='EASTMAN' where library like 'Pinawa Public Library';
update libraries set town='Portage la Prairie', region='CENTRAL' where library like 'Portage La Prairie Regional Library';
update libraries set town='Rivers', region='WESTMAN' where library like 'Prairie Crocus Regional Library';
update libraries set town='Rapid City', region='WESTMAN' where library like 'Rapid City Regional Library';
update libraries set town='Reston', region='WESTMAN' where library like 'Reston District Library';
update libraries set town='Rossburn', region='PARKLAND' where library like 'Rossburn Regional Library';
update libraries set town='Baldur', region='WESTMAN' where library like 'R.M. of Argyle Public Library';
update libraries set town='Russell', region='PARKLAND' where library like 'Russell & District Regional Library - Main';
update libraries set town='Binscarth', region='PARKLAND' where library like 'Russell & District Library - Binscarth';
update libraries set town='Ste. Rose du Lac', region='PARKLAND' where library like 'Ste. Rose Regional Library';
update libraries set town='Selkirk', region='INTERLAKE' where library like 'Red River North Regional Library';
update libraries set town='Snow Lake', region='NORMAN' where library like 'Snow Lake Community Library';
update libraries set town='Altona', region='CENTRAL' where library like 'South Central Regional Library - Altona';
update libraries set town='Morden', region='CENTRAL' where library like 'South Central Regional Library - Morden';
update libraries set town='Winkler', region='CENTRAL' where library like 'South Central Regional Library - Winkler';
update libraries set town='Stonewall', region='INTERLAKE' where library like 'South Interlake Regional Library - Main';
update libraries set town='Teulon', region='INTERLAKE' where library like 'South Interlake Regional Library - Teulon';
update libraries set town='Melita', region='WESTMAN' where library like 'Southwestern Manitoba Regional Library - Main';
update libraries set town='Napinka', region='WESTMAN' where library like 'Southwestern Manitoba Regional Library - Napinka';
update libraries set town='Pierson', region='WESTMAN' where library like 'Southwestern Manitoba Regional Library - Pierson';
update libraries set town='Steinbach', region='EASTMAN' where library like 'Jake Epp Library';
update libraries set town='The Pas', region='NORMAN' where library like 'The Pas Regional Library';
update libraries set town='Thompson', region='NORMAN' where library like 'Thompson Public Library';
update libraries set town='Morris', region='CENTRAL' where library like 'Valley Regional Library';
update libraries set town='Brandon', region='WESTMAN' where library like 'Western Manitoba Regional Library - Brandon';
update libraries set town='Carberry', region='WESTMAN' where library like 'Western Manitoba Regional Library - Carberry/North Cypress';
update libraries set town='Glenboro', region='WESTMAN' where library like 'Western Manitoba Regional  Library - Glenboro/South Cypress';
update libraries set town='Neepawa', region='WESTMAN' where library like 'Western Manitoba Regional  Library - Neepawa';
update libraries set town='Minnedosa', region='WESTMAN' where library like 'Minnedosa Regional Library';
update libraries set town='Holland', region='CENTRAL' where library like 'Victoria Municipal Library';
update libraries set town='Emerson', region='CENTRAL' where library like 'Emerson Library';
update libraries set town='Strathclair', region='WESTMAN' where library like 'Parkland Regional Library - Strathclair';
update libraries set town='Traverse Bay', region='EASTMAN' where library like 'Bibliotheque Allard - Beaches';
update libraries set town='Lorette', region='EASTMAN' where library like 'Bibliothèque Publique Tache Public Library - Main';
update libraries set town='Hartney', region='WESTMAN' where library like 'Western Manitoba Regional - Hartney Cameron Branch';
update libraries set town='Waskada', region='WESTMAN' where library like 'Bren Del Win Centennial Library - Waskada';
update libraries set town='Peguis', region='INTERLAKE' where library like 'Peguis Community';
update libraries set town='St. Lazare', region='WESTMAN' where library like 'Parkland Regional Library - St. Lazare';
update libraries set town='Nelson House', region='NORMAN' where library like 'Thompson Public Library - Nelson House';
update libraries set town='Virden', region='WESTMAN' where library like 'Border Regional Library - Main';
update libraries set town='St. Claude', region='CENTRAL' where library like 'Bibliothèque Saint-Claude';
update libraries set town='Winnipeg', region='WINNIPEG' where library like 'Winnipeg Public Library : Interlibrary Loans';
