drop table libraries cascade;
drop table library_barcodes ;
drop table library_systems ;
drop table history_group;
drop table history_chain ;
drop table reports cascade;
drop table reports_complete ;
drop table reports_queue ;
drop table request cascade;
drop table request_chain;
drop table request_closed cascade;
drop table request_group;
drop table requests_active ;
drop table requests_history ;
drop table search_statistics ;
drop table sources ;
drop table users;
drop SEQUENCE history_chain_seq ;
drop SEQUENCE libraries_lid_seq ;
drop SEQUENCE reports_complete_seq ;
drop SEQUENCE reports_rid_seq ;
drop SEQUENCE request_chain_seq ;
drop SEQUENCE request_group_seq ;
drop SEQUENCE request_seq ;
drop SEQUENCE uid_sequence ;
